//// <auto-generated />
//using System;
//using BookAuthor.Api.DataAccess;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//#nullable disable

//namespace BookAuthor.Api.Migrations
//{
//    [DbContext(typeof(AppDbContext))]
//    [Migration("20220720185234_SeedData")]
//    partial class SeedData
//    {
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "6.0.7")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

//            modelBuilder.Entity("BookAuthor.Api.Model.Author", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<DateTime>("BirthDay")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("Authors");

//                    b.HasData(
//                        new
//                        {
//                            Id = 1,
//                            BirthDay = new DateTime(1972, 8, 1, 15, 52, 34, 258, DateTimeKind.Local).AddTicks(6101),
//                            Name = "Author One"
//                        },
//                        new
//                        {
//                            Id = 2,
//                            BirthDay = new DateTime(1987, 7, 29, 15, 52, 34, 258, DateTimeKind.Local).AddTicks(6118),
//                            Name = "Author Two"
//                        },
//                        new
//                        {
//                            Id = 3,
//                            BirthDay = new DateTime(1992, 7, 27, 15, 52, 34, 258, DateTimeKind.Local).AddTicks(6119),
//                            Name = "Author Three"
//                        });
//                });

//            modelBuilder.Entity("BookAuthor.Api.Model.Book", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<int>("AuthorId")
//                        .HasColumnType("int");

//                    b.Property<string>("ISBN10")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ISBN13")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Title")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.HasIndex("AuthorId");

//                    b.ToTable("Books");

//                    b.HasData(
//                        new
//                        {
//                            Id = 1,
//                            AuthorId = 1,
//                            ISBN10 = "4242421421",
//                            ISBN13 = "4242421421123",
//                            Title = "Title 1"
//                        },
//                        new
//                        {
//                            Id = 2,
//                            AuthorId = 1,
//                            ISBN10 = "4242421421",
//                            ISBN13 = "4242421421123",
//                            Title = "Title 2"
//                        },
//                        new
//                        {
//                            Id = 3,
//                            AuthorId = 2,
//                            ISBN10 = "4242421421",
//                            ISBN13 = "4242421421123",
//                            Title = "Title 3"
//                        },
//                        new
//                        {
//                            Id = 4,
//                            AuthorId = 3,
//                            ISBN10 = "4242421421",
//                            ISBN13 = "4242421421123",
//                            Title = "Title 4"
//                        });
//                });

//            modelBuilder.Entity("BookAuthor.Api.Model.Book", b =>
//                {
//                    b.HasOne("BookAuthor.Api.Model.Author", "Author")
//                        .WithMany("Books")
//                        .HasForeignKey("AuthorId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Author");
//                });

//            modelBuilder.Entity("BookAuthor.Api.Model.Author", b =>
//                {
//                    b.Navigation("Books");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
